//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanXe.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int IdOrder { get; set; }
        public int IdUser { get; set; }
        [Display(Name = "Mã giảm giá")]
        public Nullable<int> IdDiscount { get; set; }
        [Display(Name = "Tổng tiền ")]
        public int TotalMoney { get; set; }
        [Display(Name = "Khuyến mãi")]
        public int ReduceMoney { get; set; }
        [Display(Name = "Tiền thanh toán")]
        public int FinalMoney { get; set; }
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> DayCreate { get; set; }
        [Display(Name = "Tình trạng")]
        public byte Status { get; set; }
        public string MomoPaymentID { get; set; }
    
        public virtual DISCOUNT DISCOUNT { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}
